### ISSUE TITLE
Update Newtonsoft.Json

### ISSUE THREAD

**Issue by Khaos66** [dapplo/Dapplo.HttpExtensions#20]
`Dapplo.HttpExtensions.JsonNet` currently references version `11.0.1` of `Newtonsoft.Json` (released on 17.02.2018).

We use version 12 of `Newtonsoft.Json` and want to be able to use `Dapplo.Confluence`.

Could you upgrade the `Newtonsoft.Json` reference to `12.0.1` (released on 27.11.2018)?

This would help a lot <3

**Comment by Lakritzator** [comment]
Hi,

[it](https://www.nuget.org/packages/Dapplo.HttpExtensions.JsonNet) defines "Newtonsoft.Json (>= 11.0.2)", the >= is specifically selected, meaning it "comes" with 11.0.2 if you do not select a version yourself. You can use anything newer, as long as there are no hard incompatibilities.

Nothing prevents you to install / update your Newtonsoft.Json to 12.0.1 or newer as 12 is also horribly old.

Hope this helps.

Best wishes,
Robin

**Comment by Khaos66** [comment]
Hi! 
Thx. But that's strange then. Because I got an error about the Newtonsoft.Json not beeing found in version 11.
I'll try again and report back.

**Comment by Lakritzator** [comment]
Ok, have a look and let me know, we'll find a solution. I'm not against updating, but it shouldn't be needed, and helps others to stay on older versions (whatever the reason, I'm against staying at old versions...)

**Comment by Khaos66** [comment]
I worked it out.
For direkt references this can be used in .csproj
```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
<ItemGroup>
  <PackageReference Include="Dapplo.Confluence" Version="1.0.29" />
  <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
</ItemGroup>
```

But this is an optional module for us, so I needed a more dynamic way to load this.
That's why we load it via `Assembly.LoadFile`.
To have the same effect as BindingRedirects one can use this:
```C#
[...]
{
   AppDomain.CurrentDomain.AssemblyResolve += this.CurrentDomain_AssemblyResolve;
}

private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
{
   var oAssembly = new AssemblyName(args.Name);
   if (oAssembly.Name == "Newtonsoft.Json")
   {
       return typeof(Newtonsoft.Json.ConstructorHandling).Assembly;
   }
   return null;
}
```

**Comment by Lakritzator** [comment]
Yes, the way you reference it in the .csproj is what I mean, that works for "normal" projects, it just overrides the version with your own.

But with the added information I now understand the issue you were having.
In that case, I understand what you do, help the assembly resolving to figure out what version to use.
But that does make it harder to maintain, maybe there is another solution if Newtonsoft.Json is already loaded.

Assembly.LoadFile should be used **with a lot of caution**, [I would know, see here](https://github.com/dapplo/Dapplo.Addons)...
Maybe you should consider Assembly.LoadFrom, instead of Assembly.LoadFile: [read docs here](https://docs.microsoft.com/en-us/archive/blogs/suzcook/loadfile-vs-loadfrom). I believe this takes any assembly which is already loaded, so you would not use your workaround, simplifying the maintenance. 

But it doesn't always work, depends if you do other naughty stuff. Anyway I've been there... look at this complex code (part of a WAY more complex project): https://github.com/dapplo/Dapplo.Addons/blob/master/src/Dapplo.Addons.Bootstrapper/Resolving/AssemblyResolver.cs
So maybe spend some time trying it without your Resolve workaround and use Assembly.LoadFrom, if possible.

In .NET 5+ some things have changed, I actually backported some of the .NET functionality for .NET Framework 4.7.2 in my project here: https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting
But assembly loading is a pain...
